tricore: fix runtime errors of integer overflow
aquynh/capstone pull request #2204
Opened 2023-11-20 02:36 UTC by imbillow

closes #2188

Also added SafeInt(https://github.com/dcleblanc/SafeInt) library for overflow checking, it's a header file ONLY library so I guess it should be fine?

2023-11-20 23:52 UTC, XVilka commented
@kabeor @Rot127 what are your thoughts on this?

2023-11-21 17:04 UTC, Rot127 requested changes
Generally I approve this. Though I am not sure if the `safe_math` library is not a little too much.

I guess, it makes sense for TriCore to use it, because the LLVM implementation is not part of the LLVM-project and has therefore lower quality standards.
Though for archs of the officially supported archs we can be fairly certain that they handled these things.
So the library can't be used for them.

And even if we decide to replace every arithmetic operation in ARM, AArch64 etc. with the safe version, we would need to implement an additional automation step. It will take quite some work.

So the main question is, is it worth to add all of `safe_math` just for two or three archs? I tend to think no.

I would propose two options:

1. Minimize the amount of code added: Maybe we can keep only the functions which are needed for TriCore and add a comment in the `safe_math` files where to get get the other functions if needed.
2. (My favorite). TriCore has a max. instructions width of 32bit, right? If yes, we can just run every byte sequence (`0x0 - 0xffffffff`) once on this code here (with `safe_math`). On my machine this takes roughly 5h.
If, after an overflow, CS aborts,you can implement a check for this specific case.
After all cases are fixed, we can remove `safe_math` again, because all the cases where it overflows are handled. Would this work?

2023-11-26 07:25 UTC, XVilka approved these changes
@Rot127 take a look again please

2023-11-27 14:50 UTC, Rot127 approved these changes
Nice. Way cleaner now! Just address the last two things please.

2023-11-27 14:50 UTC, Rot127 commented on arch/TriCore/TriCoreInstPrinter.c
> +static int32_t to_u32(int64_t x)
It says `u32` but casts to signed `int32_t`. Shouldn't it be `i32` or something?

2023-11-27 14:50 UTC, Rot127 commented on arch/TriCore/TriCoreInstPrinter.c
> +			       (to_u32(disp) << 1));
Run clang-format please.

2023-11-28 04:01 UTC, imbillow commented on arch/TriCore/TriCoreInstPrinter.c
> +			       (to_u32(disp) << 1));
I've already run clang-format, even though I'm using version 17.0.1.

2023-11-28 10:59 UTC, XVilka commented
@kabeor I think this one could be merged now. cc @Rot127

2023-11-28 15:13 UTC, Rot127 approved these changes
@kabeor Your turn :)

2023-11-29 16:20 UTC, kabeor commented
LGTM, thanks! Merged.

2023-11-29 16:20 UTC, merged