Add support for architecture registration
aquynh/capstone pull request #2252
Opened 2024-01-18 22:10 UTC by oleavr

To support building a static Capstone with many supported architectures and only paying for the ones needed in each consumer. In this way they won't have to build multiple copies of Capstone to minimize footprint.

2024-01-19 12:28 UTC, Rot127 requested changes
The `CAPSTONE_USE_ARCH_REGISTRATION` is missing in the `cmake` build (docs and `CMakeLists.txt`). So `cmake` will complain:
```
cmake .. -DCAPSTONE_USE_ARCH_REGISTRATION=1
Enabling CAPSTONE_ARM_SUPPORT
Enabling CAPSTONE_AARCH64_SUPPORT
...
Enabling CAPSTONE_TRICORE_SUPPORT
Enabling CAPSTONE_ALPHA_SUPPORT
-- Configuring done (0.0s)
-- Generating done (0.1s)
CMake Warning:
  Manually-specified variables were not used by the project:

    CAPSTONE_USE_ARCH_REGISTRATION


-- Build files have been written to: /home/user/repos/capstone/build

```

Please update is as well. You can ignore the `make` build. It's considered deprecated.

2024-01-19 12:28 UTC, Rot127 commented on cs.c
> +static uint32_t all_arch;
In `cs.c:1066` there is a NULL check missing before `arch_option` is called. Please add this as well.

2024-01-19 13:37 UTC, oleavr commented
@Rot127 Thanks for reviewing! The review feedback should now be addressed.

2024-01-19 15:05 UTC, XVilka approved these changes

2024-01-20 11:50 UTC, Rot127 approved these changes

2024-01-20 13:48 UTC, kabeor commented
Cool, merged.

2024-01-20 13:48 UTC, merged