[CMake] Architecture definition fix
aquynh/capstone pull request #2272
Opened 2024-02-15 00:46 UTC by Rot127

With https://github.com/capstone-engine/capstone/pull/2252 I had the trouble, that the arch support flags were not added for whatever reason. This fixes it and adds some generic `cstool` tests.
The `cstool` tests are only there to check, if the disassembler engines of each arch is reached.

2024-02-15 01:13 UTC, Rot127 commented
@kabeor It seems like the CI is unbroken again? Can you please re-trigger the workflows for the other PRs?

2024-02-15 06:40 UTC, XVilka approved these changes

2024-02-15 07:56 UTC, kabeor requested changes

2024-02-15 07:56 UTC, kabeor commented on .github/workflows/CITest.yml
> +        cstool -d x64 0x4 | grep "ERROR: invalid assembly code"
It should be better if we put all commands in a .sh file

2024-02-21 13:28 UTC, XVilka approved these changes

2024-02-23 05:20 UTC, merged