HPPA dissassembler fix unitialized variables errors
aquynh/capstone pull request #2309
Opened 2024-04-06 12:21 UTC by R33v0LT

**Detailed description**
This PR fixes errors like `unitialized variables` when using clang with flags `-Wall -Winvalid-pch -Werror -O3 --std=gnu99 -Werror=sizeof-pointer-memaccess`

**Closing issues**

closes #2304

2024-04-07 05:12 UTC, Rot127 requested changes

2024-04-07 05:12 UTC, Rot127 commented on cstool/cstool_hppa.c
> +		case HPPA_OP_INVALID:
Please add a `default` case before.

2024-04-07 05:15 UTC, Rot127 commented
Also, please fill out the complete PR description (I update it for you). We have stricter requirements now.

2024-04-10 04:46 UTC, Rot127 approved these changes

2024-04-10 05:49 UTC, kabeor approved these changes

2024-04-10 05:49 UTC, merged

2024-04-10 05:49 UTC, kabeor commented
Thank you!