check if decode[idx] is callable
aquynh/capstone pull request #2322
Opened 2024-04-12 07:26 UTC by Ced2911

idx can be bigger than 256, this pr will check the size of decode before calling it

2024-04-15 07:03 UTC, Rot127 requested changes

2024-04-15 07:03 UTC, Rot127 commented on arch/SH/SHDisassembler.c
> +	if (idx < sizeof(decode)/sizeof(decode[0]) &&  decode[idx]) {
Please use the macro `ARR_SIZE` from `utils.h` for this:

```suggestion
	if (idx < ARR_SIZE(decode) && decode[idx]) {
```

2024-04-22 07:51 UTC, Rot127 approved these changes

2024-04-23 13:58 UTC, kabeor approved these changes
Thank you!

2024-04-23 13:58 UTC, merged