Add eBPF bswap16/32/64 instruction
aquynh/capstone pull request #2323
Opened 2024-04-15 08:13 UTC by chengshuyi

**Detailed description**

Supports bswap16/32/64 instructions. Different from the le or be instructions, the opcode of bswap is BPF_ALU64.

```
// copy from: https://docs.kernel.org/bpf/standardization/instruction-set.html
BPF_ALU64 | BPF_TO_LE | BPF_END with imm = 16/32/64 means:

  dst = bswap16(dst)
  dst = bswap32(dst)
  dst = bswap64(dst)
```

2024-04-16 05:14 UTC, Rot127 requested changes
Thanks for the addition!

Please fill out the complete PR template. Not just the description. No need document the functions. Since this plugin gets refactored to auto-sync sooner or later anyways.

Necessary though is a test case in `suite/cs_test/issues.cs`.

2024-04-16 05:14 UTC, Rot127 commented on arch/BPF/BPFMapping.c
> +			case (16 << 4):
Please add the `default` case.

2024-04-16 05:14 UTC, Rot127 commented on arch/BPF/BPFMapping.c
> +			case (16 << 4):
Some compilers might complain

2024-04-16 09:00 UTC, Rot127 approved these changes

2024-04-23 14:04 UTC, kabeor approved these changes
Cool, thank you!

2024-04-23 14:04 UTC, merged