Restructure auto-sync docs to have them more contained
aquynh/capstone pull request #2355
Opened 2024-05-11 09:28 UTC by Rot127

**Your checklist for this pull request**
- [ ] I've documented or updated the documentation of every API function and struct this PR changes.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

The auto-sync documentation was spread around and confusing. This is an attempt to move it closer together and remove duplicate (and contradicting) instructions.

**Test plan**

...

**Closing issues**

...

2024-05-31 12:48 UTC, XVilka requested changes
@numas13 you might be interested in quickly skimming these documents as well.

2024-05-31 12:48 UTC, XVilka commented on suite/auto-sync/ARCHITECTURE.md
> +# Architecture of Auto-Sync
"Architecture of Auto-Sync tool" or "Architecture of Auto-Sync framework". Something like that. Otherwise it sounds *incomplete*.

2024-05-31 12:48 UTC, XVilka commented on suite/auto-sync/README.md
> +Install auto-sync
Same, "auto-sync framework" or "tool"

2024-05-31 12:48 UTC, XVilka commented on suite/auto-sync/README.md
> +  python3.11 -m usort format src/autosync
Is there any reason to hardcode `python3.11` here? Maybe generic `python3` is enough?

2024-05-31 12:48 UTC, XVilka commented on suite/auto-sync/README.md
> +## Refactor an architecture for `auto-sync`
Same.

2024-05-31 12:48 UTC, XVilka commented on suite/auto-sync/intro.md
> +## Why AutoSync?
Please be consistent, it's "Auto-Sync" in one place and "AutoSync" in another.

2024-06-01 15:34 UTC, XVilka approved these changes

2024-06-02 11:44 UTC, XVilka commented
@kabeor this one is ready to be merged too.

2024-06-08 07:29 UTC, XVilka commented
@kabeor @aquynh

2024-06-10 01:54 UTC, kabeor approved these changes

2024-06-10 01:55 UTC, merged