[next][SuperH] Fix missing setting detail->sh
aquynh/capstone pull request #2466
Opened 2024-08-31 17:59 UTC by david942j

detail->sh is never set. Which makes the detailed output related to operands is always missing.

 

**Your checklist for this pull request**
- [x] I've documented or updated the documentation of every API function and struct this PR changes.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

`detail->sh` is never set. Which makes the detailed output related to operands is always missing.

**Test plan**

`build/suite/cstest/cstest tests/issues/issues.yaml`, the newly added case passes/fails with/without the change.

**Closing issues**

closes #2424 (along with #2465)

2024-09-01 07:27 UTC, Rot127 requested changes
Please delete the binary.
The failing clang-tidy test is because there are unrelated problems.
I asked @lhsazevedo in https://github.com/capstone-engine/capstone/pull/2389 already to fix it.
I you want to you can of course open a PR to his branch to speed things up.

2024-09-01 07:27 UTC, Rot127 commented on tests/test_arm64
Please remove the binary

2024-09-01 07:58 UTC, david942j commented on tests/test_arm64
Oops. Done.

2024-09-09 10:44 UTC, Rot127 approved these changes

2024-09-09 10:45 UTC, Rot127 commented
Please rebase though and fix the conflicts. The clang-tidy job can be ignored. It is fixed in the coverity PR.

2024-09-14 06:56 UTC, Rot127 commented
@david942j The clang-tidy issues are fixed in https://github.com/capstone-engine/capstone/pull/2469. But I cannot merge, so we have to wait until @kabeor finds time to review and merges stuff.

2024-09-18 17:12 UTC, david942j commented
@kabeor I just resolved conflicts with the latest next branch, this PR is ready to be reviewed, thanks!

2024-09-19 08:18 UTC, Rot127 approved these changes

2024-09-19 11:03 UTC, kabeor approved these changes
Cool, thanks.

2024-09-19 11:03 UTC, merged