AArch64: Replace vararg add_cs_detail by multiple concrete functions
aquynh/capstone pull request #2507
Opened 2024-10-13 15:52 UTC by thestr4ng3r

**Your checklist for this pull request**
- [x] I've documented or updated the documentation of every API function and struct this PR changes.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible) - current tests should be sufficient.

**Detailed description**

Fixes UB caused by various mismatches on how these arguments are passed and read. This became visible when running on PowerPC hosts with e.g. `cstool -d aarch64 204862f8`.
Apart from the UB fix, this is meant to be a pure refactor.

**Test plan**

see https://github.com/capstone-engine/capstone/issues/2458#issuecomment-2389210291

**Closing issues**

Partially addresses #2458
Mips, PPC and Xtensa still have potentially problematic varargs.

2024-10-13 16:27 UTC, thestr4ng3r commented
I need to fix auto-sync tests, but the approach can be reviewed nonetheless.

2024-10-14 11:49 UTC, Rot127 requested changes
Please add the instruction from above as test in a file in `tests/issues/`.

2024-10-16 16:34 UTC, thestr4ng3r commented
Added. Keep in mind the bug in the original code does not manifest itself on current mainstream architectures.

2024-10-17 11:40 UTC, Rot127 commented
> Added. Keep in mind the bug in the original code does not manifest itself on current mainstream architectures.

Yes, I am aware. But I want to have it in case someone starts using Capstone on another weird machine. So just general test case coverage.

2024-10-17 11:41 UTC, Rot127 approved these changes
@kabeor

2024-10-19 04:08 UTC, kabeor approved these changes
Cool, can you help to solve the conflict so I can merge it?

2024-10-21 20:03 UTC, thestr4ng3r commented
Sure, rebased now.

2024-10-22 13:11 UTC, merged