tricore: fixes #2474
aquynh/capstone pull request #2523
Opened 2024-10-22 07:29 UTC by imbillow

**Your checklist for this pull request**
- [ ] I've documented or updated the documentation of every API function and struct this PR changes.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

ref https://github.com/capstone-engine/llvm-capstone/pull/63

**Test plan**

...

**Closing issues**

closes #2474

2024-10-22 08:26 UTC, imbillow commented
I added the A15 register to the `Defs` attribute, but this only has implicit register modification information, and there is still no A15 in the operands meta information.

```
let Defs = [A15] in
...
```

```
cstool -d tc162 d800
 0  d8 00  ld.a a15, [sp]#0
        ID: 164 (ld.a)
        op_count: 1
                operands[0].type: IMM = 0x0
                        .access: READ
        Registers modified: a15
        Groups: HasV120_UP
```

2024-10-22 10:08 UTC, Rot127 commented
Mh, I think we can go the expensive way for now. If one of the implicit registers commonly used in the asm text (`a15`, `a10` etc.) are in the implicit list, check if they are in the asm text (with `strstr()`). if yes, insert them at the correct position.

So basically:

- `a15` in implicit read/write?
- If yes: Check if `a15` in asm text
- If yes: insert into details.

Same for the other registers like `a10`.

2024-10-22 10:11 UTC, Rot127 commented
Just had another idea. WHat if you add another operand class in the `td` files. For those registers.
You can assign a printing method to them. And a decoding method. For example: `printImplicitA15()`, `printImplicitA10()`.
The decoding methods do nothing. And the print methods just adds the register to the details.
Do you think this would be easier?

2024-10-23 19:07 UTC, imbillow commented
Both PRs should be ready for review now. @Rot127 

cc @XVilka

2024-10-24 12:38 UTC, Rot127 requested changes
It looks like the correct fix. Very nice! So far it only fixes the `ld.a` instruction.

But we need also the other ones (see comment below. Effectively, all instructions with operands in `TriCoreGenAsmWriter.inc::AsmStrs`).

Just an observation: We never use `TriCoreGenInstrInfo.inc::TriCoreInstrTable::ImplicitOps`. Maybe they are a way to a quick fix? E.g. you can save them in an `MCInst` field and after printing, check if those names appear in the asm text.

But they seem to miss `D15` and the access information. So only a little bit useful.
Maybe it misses `D15` because they have the same value as `A15`?

Please add two more things:

- Tests in `test/issues/`
- Add TriCore to `.github/workflows/auto-sync.yaml` with the other architectures.

2024-10-24 12:38 UTC, Rot127 commented on arch/TriCore/TriCoreGenAsmWriter.inc
> +  /* 3321 */ "st.w [sp]\0"
I think some instructions are not handled yet in the td files?

2024-10-24 12:52 UTC, Rot127 commented on arch/TriCore/TriCoreGenAsmWriter.inc
> +  /* 3321 */ "st.w [sp]\0"
Ok, I am stupid. Wrong file -.-

2024-10-25 13:38 UTC, Rot127 approved these changes
Excellent! Thanks a lot.

Please just open an issue about the known access problems.

2024-10-25 13:38 UTC, Rot127 commented on tests/details/tricore.yaml
> +                  access: CS_AC_WRITE # fixme: should be read
Please open an issue about it.

2024-10-25 13:38 UTC, Rot127 commented on tests/details/tricore.yaml
> +                  access: CS_AC_READ # fixme: should be write
Also this one.

2024-10-25 13:38 UTC, Rot127 commented on tests/details/tricore.yaml
> +                  access: CS_AC_READ # fixme: should be write
And below

2024-10-28 13:32 UTC, XVilka approved these changes
@Rot127 please take a look again, it looks good to merge, I think.

2024-10-29 10:50 UTC, Rot127 approved these changes
@kabeor

2024-11-01 09:30 UTC, kabeor approved these changes
Thanks again!

2024-11-01 09:30 UTC, merged