Implement CPack for Debian/RPM
aquynh/capstone pull request #2590
Opened 2024-12-22 19:21 UTC by AndrewQuijano

**Your checklist for this pull request**
- [ X ] I've documented or updated the documentation of every API function and struct this PR changes.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**
I created a CPackConfig.txt that can create both Debian and RPM packages. The Debian package matches what we have now. I can look further about making a proper RPM package.

I do want to get help with macOS package creation and testing using CPack

I updated how to do this in the Building.md file
...

**Test plan**
We can probably use something like check_capstone.sh? Although for now, we can merge it as another way to create the Debian Package? My hope is, from here, work can be done to get a Mac OSX package built. I can help with RPM, the work is done, but any last necessary touches I can take care of it.

...

**Closing issues**

...

2024-12-27 02:37 UTC, AndrewQuijano commented
@Rot127 While I will need help with the Mac stuff, I can try to poke around how capstone made RPM packages before.

I do want to ask, if the goal is to automate placing Debian packages in APT, this would require creating both a libcapstone package with the shared objects only and another debian with the static library/headers. I could use cmake twice and leverage CPack to make two packages. To avoid the headers being made twice, would I need to delete these lines of code?

https://github.com/capstone-engine/capstone/blob/next/CMakeLists.txt#L799-L801

2024-12-29 15:40 UTC, Rot127 commented
Sorry for the late answer. I will review this one after new year. But to answer your questions meanwhile:

> I do want to ask, if the goal is to https://github.com/capstone-engine/capstone/issues/2537, this would require creating both a libcapstone package with the shared objects only and another debian with the static library/headers.

Yes, this would be nice to have. Though, I can't put any priority on it. And before v6 Beta, it is not necessary. I think for v6 Gold it is though.

> try to poke around how capstone made RPM packages before, but your feedback would be helpful to have!

I have no idea. They were made before my time here. You have to contact the package maintainers and/or follow the [docs](https://rpm-packaging-guide.github.io/).

2024-12-31 00:13 UTC, AndrewQuijano commented
I poked around a bit more about making the RPM the best I can, so a few things I'll likely need help on,
I will ask based on this
https://github.com/capstone-engine/capstone/blob/next/packages/rpm/capstone.spec

1. It would be nice to have something to check if the package works, is this legit?
```
ln -s libcapstone.so libcapstone.so.5
make check LD_LIBRARY_PATH="`pwd`"
```

2. It would be nice to have an install too, would this look accurate to add?
```
DESTDIR=%{buildroot} LIBDIRARCH=%{_lib} \
INCDIR="%{_includedir}" make install
find %{buildroot} -name '*.la' -exec rm -f {} ';'
find %{buildroot} -name '*.a' -exec rm -f {} ';'

# install python bindings
pushd bindings/python
%{__python2} setup.py install --skip-build --root %{buildroot}
%if 0%{?with_python3}
%{__python3} setup.py install --skip-build --root %{buildroot}
%endif # with_python3
popd

# install java bindings
install -D -p -m 0644 bindings/java/%{name}.jar  %{buildroot}/%{_javadir}/%{name}.jar
```

3. I'm not sure if a build would be need for the package?
```
DESTDIR="%{buildroot}" 	V=1 CFLAGS="%{optflags}" \
LIBDIRARCH="%{_lib}" INCDIR="%{_includedir}" make %{?_smp_mflags}

# Fix pkgconfig file
sed -i 's;%{buildroot};;' capstone.pc
grep -v archive capstone.pc > capstone.pc.tmp
mv capstone.pc.tmp capstone.pc

# build python bindings
pushd bindings/python
CFLAGS="%{optflags}" %{__python2} setup.py build
%if 0%{?with_python3}
CFLAGS="%{optflags}" %{__python3} setup.py build
%endif # with_python3
popd

# build java bindings
pushd bindings/java
make CFLAGS="%{optflags}" # %{?_smp_mflags} parallel seems broken
popd
```

4. Please feel free to check my current generated spec file and poke around what else should be needed to make this as high quality as possible

2025-01-03 17:38 UTC, Rot127 requested changes
Nice! Thanks a lot for getting started with it.

Some general notes:

- Let's exclude OSX for now, please. It gets too much otherwise and they can be part of another PR.
- The `packages/rpm/capstone.spec` file shouldn't be necessary. I think it can be removed. CPack should generate it.
- Once we have tested the package build locally, we can add the process to the release workflow.

Regarding https://github.com/capstone-engine/capstone/pull/2590#issuecomment-2566026481

This looks a little hacky. Let's not worry about the bindings for now. Because they need some refactoring before (see: https://github.com/capstone-engine/capstone/discussions/2291).
And maybe there are way better ways to create such packages. In the case of the Python bindings, they are already uploaded to [pypi](https://pypi.org/project/capstone/).

2025-01-03 17:38 UTC, Rot127 commented on CPackConfig.txt
> +set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "lightweight multi-architecture disassembly framework - devel files")
```suggestion
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Lightweight multi-architecture disassembly framework - devel files")
```

2025-01-03 17:38 UTC, Rot127 commented on CPackConfig.txt
> +endif()
Those need to be set depending on the current build.

[CMAKE_SYSTEM_PROCESSOR](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html#variable:CMAKE_SYSTEM_PROCESSOR) seems to report the architecture. Except for Windows 32bit. For which it wrongly reports `amd64`.

But you can correct it by checking a `CMAKE_SIZE_OF_VOID_P` like [here](https://discourse.cmake.org/t/how-to-distinguish-windows-architecture/5104).

Just save the actual target architecture to a new variable and use it here.

2025-01-03 17:38 UTC, Rot127 commented on CPackConfig.txt
> +set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "lightweight multi-architecture disassembly framework - devel files")
Regarding the `devel files` part:

This should only be in there if the package contains the headers. Otherwise the name is wrong. According to the [docs](https://cmake.org/cmake/help/latest/module/CPack.html), all things installed via `install()` are added to the package. So, it is probably better to add a `CAPSTONE_USER_PGK` flag or similar. And when it is present the headers are not installed.
Then just run `CPack` twice to get both packages.

Then you can check for the presence of the variable and set the name differently.

For the graphical installer there seems to be the [CPackComponent](https://cmake.org/cmake/help/latest/module/CPackComponent.html#module:CPackComponent) feature. But this can be postponed.

2025-01-03 17:38 UTC, Rot127 commented on CPackConfig.txt
> +set(CPACK_RPM_PACKAGE_LICENSE "/usr/share/doc/libcapstone-dev/LICENSES")
SAme here. The `-dev` in the name

2025-01-03 17:38 UTC, Rot127 commented on packages/rpm/uninstall.sh
I am fairly sure this won't work. It doesn't respect host architecture. Also, users can decide to install the package somewhere else IIRC.

Why do we need it anyways?

2025-01-03 17:38 UTC, Rot127 commented on packages/rpm/remove_blank_lines.sh
Why is this necessary?

2025-01-03 17:38 UTC, Rot127 commented on CPackConfig.txt
> +set(CPACK_BUNDLE_PLIST "xcode/CapstoneFramework/Info.plist")
I propose to skip OSX for now. It just gets too much. in this PR.

2025-01-05 19:59 UTC, AndrewQuijano commented on CPackConfig.txt
> +set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "lightweight multi-architecture disassembly framework - devel files")
Currently the RPM and Debian package will have headers, .a and .so libraries.

2025-01-05 20:08 UTC, AndrewQuijano commented
@Rot127 Just updated the CPack file per your suggestions, two questions remain:
1. Is there a way to test the package after the installation to confirm it works?
2. Have you had a minute to check if the RPM package works as intended?

https://github.com/AndrewQuijano/capstone/releases/tag/6.0.1

2025-01-06 19:25 UTC, Rot127 commented
> Is there a way to test the package after the installation to confirm it works?

I just ran a `cstool` command the last time to check. Because `cstool` uses the dynamic library.
For headers we can just check, if we can include them as system header in a C source file.
  
> Have you had a minute to check if the RPM package works as intended?

Not yet. I waited for you to add the workflow job, so I don't have to set up to much. Will do it!

> Once this is tested, should I delete all the docker stuff from the deb folder too?

Yeah, sure. Less duplicates are always better.

> Should I also replicate this on v5 branch as I do still really hope to get a v5.0.4 package ready for faster PANDA installation relatively soon

This would be awesome!

@kabeor Do you know if we could get the release before lunar new year?
If you have enough time, @AndrewQuijano can open the PR now and we can prioritize it. So it is merged quickly.

2025-01-07 05:16 UTC, AndrewQuijano commented
@Rot127 What are the cstool commands you used? I think I can add this to RPM spec file? I just removed the duplicate with Docker and created the PR for v5.

I should note, it seems I broke labeler when switching to v5, I'm trying to fix this, but it is turning out to be a bit more complicated than I thought

https://github.com/actions/labeler

2025-01-08 13:28 UTC, Rot127 commented
> I should note, it seems I broke labeler when switching to v5, I'm trying to fix this, but it is turning out to be a bit more complicated than I thought

No worries. The labeler problem is likely this one: https://github.com/actions/labeler/issues/710
It is also broken in other PRs.

2025-01-08 14:37 UTC, Rot127 requested changes
I made the review on this one. Since they the comments are basically the same for the `v5` version.

Btw, I am sorry if I sometimes make multiple suggestions on the same line of code. I learn how the CPack packaging works while reviewing your code. So sometimes I see things only on a second look.

Hope this is not discouraging. I very much appreciate your effort!

2025-01-08 14:37 UTC, Rot127 commented on .github/labeler.yml
Please, revert this change. You can open another PR with it.

On a second thought. Also the removal of the `travis.yml`.
Just so we have clear separations between changes made.

2025-01-08 14:37 UTC, Rot127 commented on .github/workflows/labeler.yml
> +    - uses: actions/labeler@v5
Please revert as well. It is done in:
https://github.com/capstone-engine/capstone/pull/2598

2025-01-08 14:37 UTC, Rot127 commented on packages/rpm/postinstall.sh
> +/sbin/ldconfig
According to [this](https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_default_shell) you can just run `ldconfig` and don't need a shebang. So better just make this `ldconfig`.

Just to prevent any problems with paths, non-existent binaries etc.

2025-01-08 14:37 UTC, Rot127 commented on CPackConfig.txt
> +    DESTINATION "/usr/share/doc/libcapstone-dev"
Looking at it a second time:
This is still a hard-coded path which might lead to problems on some systems.

I think you don't need to add the README, SPONSORS etc. to the package (or is there any requirement I am not aware?).
But apparently, you can add it using https://cmake.org/cmake/help/latest/module/CPack.html#variable:CPACK_RESOURCE_FILE_LICENSE.

The license is apparently added via [CPACK_RESOURCE_FILE_LICENSE](https://cmake.org/cmake/help/latest/module/CPack.html#variable:CPACK_RESOURCE_FILE_LICENSE)

Please check for the others.

2025-01-08 14:37 UTC, Rot127 commented on CPackConfig.txt
> +# set(CPACK_RPM_PACKAGE_RELEASE "6.fc42")
```suggestion
```

2025-01-08 14:37 UTC, Rot127 commented on CPackConfig.txt
> +# set(CPACK_BUNDLE_PLIST "xcode/CapstoneFramework/Info.plist")
Remove unused code. Please open an issue about it when this is merged. Although, IMHO, For the CPack generated packages we don't need desperately tests. I think it is reasonable to trust the CPack folks.

2025-01-08 14:37 UTC, Rot127 commented on CPackConfig.txt
> +    DESTINATION "/usr/share/doc/libcapstone-dev"
As described above, please use the CPack functionality to add the licenses.

2025-01-08 14:37 UTC, Rot127 commented on LICENSES/LICENSE_PACKAGE.txt
> +The scope of this license is the `packages/deb` and `packages/rpm` directory, `CPackConfig.cmake` and `CPackConfig.txt'
Ah nice, missed those before.

You can add [SPDX headers](https://spdx.dev/learn/handling-license-info/) to all your file headers with the MIT copyright and remove this file. Something like this

```
# Copyright © 2024 Andrew Quijano <your-mail@example.com>
# SPDX-License-Identifier: MIT
```

We will switch at some point to `reuse` for license management.

2025-01-11 20:32 UTC, AndrewQuijano commented
@Rot127 Just updated the PR, and just curious would you look into how to update labeler to v5? Also, figure I should ask, you don't mind I use your ISSUE_TEMPLATE folder and labeler stuff for any other open-source work right?

2025-01-12 15:51 UTC, Rot127 requested changes
Looks good!

But the build fails for me: https://github.com/Rot127/capstone/actions/runs/12734529842/job/35492198289

```
...
 Enabling CAPSTONE_WASM_SUPPORT
Enabling CAPSTONE_BPF_SUPPORT
Enabling CAPSTONE_RISCV_SUPPORT
Enabling CAPSTONE_SH_SUPPORT
Enabling CAPSTONE_TRICORE_SUPPORT
Enabling CAPSTONE_ALPHA_SUPPORT
Enabling CAPSTONE_HPPA_SUPPORT
Enabling CAPSTONE_LOONGARCH_SUPPORT
Enabling CAPSTONE_XTENSA_SUPPORT
CMake Error at /usr/local/share/cmake-3.31/Modules/WriteBasicConfigVersionFile.cmake:43 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/local/share/cmake-3.31/Modules/CMakePackageConfigHelpers.cmake:402 (write_basic_config_version_file)
  CMakeLists.txt:897 (write_basic_package_version_file)


-- Configuring incomplete, errors occurred!
```

2025-01-12 15:51 UTC, Rot127 commented on .github/workflows/build_release.yml
> +
While testing I thought it would be nice to upload the produced packages also as artifacts.

So we don't need a release each time we want to download them.

```
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./build/*
```

2025-01-12 15:51 UTC, Rot127 commented on CPackConfig.cmake
The build possibly fails due to this name.
`CPackConfig.cmake` is a reserved name IIRC. Try to rename it to `CPackGeneratorSetup.txt` or something like this.

2025-01-12 15:53 UTC, Rot127 commented
> Just updated the PR, and just curious would you look into how to update labeler to v5? 

It isn't a priority currently for me. Too much other stuff to do unfortunately. If you want to work on it feel free to do so! If you are faster then @kabeor reviewing, we can replace my downgrading PR with yours.

> Also, figure I should ask, you don't mind I use your ISSUE_TEMPLATE folder and labeler stuff for any other open-source work right?

Not at all. It is open-source in the end :D

2025-01-12 23:34 UTC, AndrewQuijano commented on .github/workflows/build_release.yml
> +
@Rot127 Would I add this to the release workflow? It just seems like this would mean the artifact would only be made on release unless I put it on another workflow?

Please add the commit so I can add it to this PR

2025-01-12 23:46 UTC, AndrewQuijano commented on CPackConfig.cmake
- The issue is the version `v110.0.0`, so I will update the regex to remove the 'v' or 'V' in front of the version argument. Note this also works with current debian packaging standard e. g. `6.0.0-Alpha2`
-

2025-01-13 00:05 UTC, AndrewQuijano commented on CPackConfig.cmake
let me know if the regex should be stricter to remove/ignore all numbers before the X.Y.Z?

```
string(REGEX MATCH "^[vV]?([0-9]+\\.[0-9]+\\.[0-9]+)" _ ${PROJECT_VERSION})
set(PROJECT_VERSION_BASE ${CMAKE_MATCH_1})
```

2025-01-13 15:50 UTC, Rot127 commented on .github/workflows/build_release.yml
> +
Yeah, sorry. Oversaw this. Ignore it for now. We can add it later.

2025-01-13 16:42 UTC, Rot127 commented
Debian works fine.
But the rpm package fails to install:

```
nothing proivdes libc6 >= 2.2.5
```

The package name for `libc` is apparently [glibc](https://packages.fedoraproject.org/pkgs/glibc/glibc/fedora-rawhide.html) (tested on Fedora). Also see https://packages.fedoraproject.org/pkgs/capstone/capstone/fedora-rawhide.html.

2025-01-13 18:31 UTC, AndrewQuijano commented
@Rot127 just updated CPack, hopefully this should fix the issue

2025-01-14 15:22 UTC, Rot127 approved these changes
Very nice! Thanks a lot!

2025-01-15 18:46 UTC, AndrewQuijano commented
@kabeor Please merge and create a 5.0.4 on the v5 Branch

2025-01-16 08:35 UTC, kabeor commented
> @kabeor Please merge and create a 5.0.4 on the v5 Branch

Done.

2025-01-16 14:54 UTC, AndrewQuijano commented
@kabeor Thank you for the new release! I'm wondering, would it be possible to re-release 5.0.4? It seems the code to dynamically update the version got deleted here.

![image](https://github.com/user-attachments/assets/42163a35-116d-4d39-aa1f-ac8c96a049ea)

The released packages are missing the version in the file name (I aimed to follow standard RPM/Debian package practices), since the code to dynamically pick up the version from the tag got deleted.

https://github.com/capstone-engine/capstone/releases/tag/5.0.4

Also, could you please merge #2590? I should note, this PR also has the same technique to dynamically update the version of Capstone based on input from tag name. This should save time from having to manually bump the version number for every release, which seemed to be ok with @Rot127 

I see based on the v5 release, I think a better solution is to use a version.h.in file, with some modifications from CMake, we can dynamically get this version data, automating this work on every release. Should this just be another PR?
```
#ifndef VERSION_H
#define VERSION_H

#define PROJECT_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define PROJECT_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define PROJECT_VERSION_PATCH @PROJECT_VERSION_PATCH@

#endif // VERSION_H
```

2025-01-16 15:19 UTC, AndrewQuijano commented
Two things

1- I did a bit more digging around for pkgconfig.mk, it is used by Makefile and Python, I propose having CMake be able to dynamically overwrite pkgconfig.mk with the version data if it is provided. I'm not sure where I'd write the updated version of pkgconfig for use? I'd also be curious what the values in `bindings/python/capstone/__init__.py` are used for?

![image](https://github.com/user-attachments/assets/6d96dad0-5a9c-493e-b1b1-b4ab94df835b)

2- I can add a version.h file to be created and updated dynamically in `include/capstone` folder. Let me know what to do next @Rot127 @kabeor

2025-01-16 15:31 UTC, Rot127 commented
> It seems the code to dynamically update the version got deleted here.

Just pinged him. Was an accident while resolving conflicts. Thanks for pointing it out!
@kabeor will do a `5.0.5`.

> I see based on the v5 release, I think a better solution is to use a version.h.in file, with some modifications from CMake, we can dynamically get this version data, automating this work on every release. Should this just be another PR?

Good idea. At least on the next branch we should have it.
Would you mind opening an issue about it.

Regarding the whole pkgconfig changes:
Let's do them in the next release. Not now, in the v5.0.5 one. Otherwise you have to wait even longer for it :D And we might break it while rushing.
But we can discuss details in the issue. TO have them contained at one place.

2025-01-16 15:38 UTC, Rot127 commented
@AndrewQuijano Please review https://github.com/capstone-engine/capstone/pull/2606

2025-01-16 15:46 UTC, Rot127 commented
Ah, also. Please rebase this one on the latest next. The labeler is fixed again.

2025-01-19 00:14 UTC, AndrewQuijano commented
@Rot127 Rebased complete!

2025-01-20 12:29 UTC, Rot127 approved these changes

2025-01-20 14:50 UTC, kabeor approved these changes
Thank you, merged.

2025-01-20 14:50 UTC, merged